name: ci

on:
  push:
    branches:
      [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Echo Go version
        run: go version

      - name: Test API
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log Go Formatter
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Run Go Formatter
        run: test -z $(go fmt ./...)

      - name: Install Static Check
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Static Check
        run: staticcheck ./...

  Security:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log Go Formatter
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec
        run: gosec ./...


